# Generated by Django 3.2.13 on 2022-06-02 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_item_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='small',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='item',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
