# Generated by Django 3.2.13 on 2022-06-02 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20220602_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('title',)},
        ),
    ]
