# Generated by Django 3.2.13 on 2022-06-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='photo1',
            field=models.ImageField(upload_to='static/feedback/%Y-%m-%d/'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='photo2',
            field=models.ImageField(upload_to='static/feedback/%Y-%m-%d/'),
        ),
    ]
