# Generated by Django 3.2.13 on 2022-06-03 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20220603_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='photo1',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='photo2',
        ),
    ]
