# Generated by Django 3.2.13 on 2022-06-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20220603_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='photo',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
