# Generated by Django 3.2.13 on 2022-06-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_feedback_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='photo',
            field=models.ImageField(upload_to='static/feedbacks/%Y-%m-%d'),
        ),
    ]
