# Generated by Django 3.2.13 on 2022-06-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_item_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('inst', models.URLField(max_length=150)),
                ('vk', models.URLField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('tlg', models.URLField(max_length=150)),
            ],
        ),
    ]
