# Generated by Django 3.2.13 on 2022-06-21 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='pickup',
        ),
    ]
