# Generated by Django 3.2.13 on 2022-06-24 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_item_show_on_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='size',
        ),
    ]
