# Generated by Django 3.2.13 on 2022-07-04 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20220704_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.collection'),
            preserve_default=False,
        ),
    ]
