# Generated by Django 3.2.13 on 2022-06-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.BooleanField(default=False),
        ),
    ]
