# Generated by Django 3.2.13 on 2022-06-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(default='', max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='comment',
            field=models.CharField(default='', max_length=350),
            preserve_default=False,
        ),
    ]
