# Generated by Django 3.2.13 on 2022-06-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20220616_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.PositiveIntegerField(default=300),
        ),
    ]
