# Generated by Django 3.2.13 on 2022-06-17 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_delivery_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='comment',
        ),
    ]
