# Generated by Django 3.2.13 on 2022-06-17 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_track_sended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='track_sended',
        ),
    ]
